cx-flow:
   enabled-vulnerability-scanners:
     - cxgo
   bugTracker:
     - NONE

cxgo:
  client-secret: eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.0qYtKgrtzBfIZD2OGFbM31YywYzD6YXWzL2RyiXB3tslu1-5Pigddr0OxFIOIhAdnma0-SwjFX6-p_0SRV5OLfsM0dUE34SKZgNyTqFpg15aJqJmacNgFjJKs24NZUntjgR0yuLbkJxl6T8UyG1l9wU77I9k3RdBod2bu7EuIkI6XNESg3SkhsB3rHT4dmBZ1-b21K5a2p0-nUAE_bbDZlocHcHoVr6ST_ESDoAijJl6AsF2QNTD5-kSR9WnGWYVy6zKtWt-uSe3icNoSulIAZ4ONaGtcM7OvoWIy5CVa37CW8D-p0GT78ok3FGj2wsfkTt6X-uX1KzjF7K_do14Qg.XyIRkQQ1-7yQkGWu.OjxHKtaYFuc4spUUSaqgUGtvyosvciiACN5jKX6PzqrOP65ssICRMH1kQ_DDSW021HMfkhYysypZ3C3ThCI0VUdRXVoAxHmk7oeIvwv6XSXBRUUfIhOk9BwDP7BTCxGuuHs1PMW91FD2KM6q1Ct16DRZ7Qkbi_U5hEM5c8Z0-qgevw0lFuf15vHbC0Jg0qS86b6SjeFlFxBDV6q9BLfxFNSMv74nSEjfza3VLQ_LDPphBLVwhWIHLoyfu7qEpS0ttG_jK6jE_E_IoeGsVKTyuXjdX0-E_wQaNOmV6lywspeZSCTfeDeunLiRYSkH58RFLNe4cDpj5PRXq47MtH4MEw9yIkxyP92iev8_PNdvVwvD2RGrJ-FJD4AskaEZifOmGjDf_E1hVcBe6Dif38Y1LPzFkqVzjsL_6kUwpMV7eJ538muN5H1Y8J3hRitdD5UnwvU-NckcSm25fl4ETMlZ9Lbv9-KHYxZqIlzndZOARF1VLXMAfJGHXep5oTt7Bs57biNzoFcRAKCXSrQFCsCBD0Bm8soefdSdPb5GLPujmHfgLIlxNf7id2TyItwcGehPmFiMmeZUBWKqRBpYMeMUZhFwqiuTNns2-4GbWDymuMImLePPx7UTjZyLiWfQhGlxcI5Uuy3mW2eT3mmRpbDFtPPH8ygj285fgT45W4Vo5sGOID4IwTS8W2QELSkQMaJDrzCyR3YyTh1xk9o2nR1CZMdQmQP8AZiF-sKma05Vlj8dN-muSiWYhaqs4Dutza3EWdDEGzDrKQq9U0lYBW6GRiUeb8jqtPNhKtmeVB3ewR9NwV3M7LCXb8zT7gmrw01_K5CubWvegjanpd5pgMT-scDBXBmis-TQV90VgrmTMkFTj3ggscmqCjyc4oWcjUuqU56JQmvF6ZG9RCwRjjK6yRIeZ90b_yTbGAC-GgkcEMOF_rtlbl7AVeZvJ_B_6Oxy0tiiVg22uRDeMFcwvkNz4NljzzmKu4R1MgzbIVpgdSpfqtLNEhisfQDA37m7Gf97_IZ9jGSdf3zBB4CDjVlk-hkXyCKIX5XJXsMqFMcwoDBcQ918zIU4vlrqKV58DaPmf-OXBSxTzWnfBNoO2_3En21Fyhl5RcqLX2BqrL-SHi2wcluPkVLqHwD5drYVW43smLtB-_zBzmjRm4YAq8ZTjHzcOjE6L3H5hNf3TyUHfcEDnrrrec84KGVxJLzq8F3oR3B_XocduxTeQiKYZ-6IzbBDLo-yqCpWxdMONpdGndP4IMMoDcBQcUGgS4uGUhJLceb7r3RItMnjb85ektg.IfOs39xfelXLzw7ivcWbpA:2kouih5fpp63ck9kudm4v13d9u
  base-url: https://api.checkmarx.net
  portal-url: https://cloud.checkmarx.net
  # CxGo Business unit that will contain the project/application/scan
  team: \Cx NA Team\CxPhil
  url: ${cxgo.base-url}
  multi-tenant: false
  configuration: Default Configuration
  #
  ## Available Scan defaults
  #
  #   - CXOD_MOBILE_NATIVE = 1;
  #   - CXOD_MOBILE_WEB_BASED = 2;
  #   - CXOD_DESKTOP_NATIVE = 3;
  #   - CXOD_DESKTOP_WEB = 4;
  #   - CXOD_API = 5;
  #   - CXOD_FRONTEND = 6;
  #   - CXOD_BACKEND = 7;
  #   - CXOD_LAMBDA = 8;
  #   - CXOD_CLI = 9;
  #   - CXOD_SERVICE = 10;
  #   - CXOD_SMART_DEVICE = 11;
  #   - CXOD_OTHER = 12;
  scan-preset: 1
