version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch
      #- image: docker.io/checkmarx/cx-flow
    steps:
      - checkout
 
      #- run:
      #    name: Install CxCLI Plugin
      #    command: |
      #      wget -O ~/cxcli.zip https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-2020.4.4.zip
      #      unzip ~/cxcli.zip -d ~/cxcli
      #      chmod +x ~/cxcli/runCxConsole.sh
      
      - run:
          name: Install CxFlow Plugin
          command: |
            wget -O ~/cxflow.jar https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.15/cx-flow-1.6.15.jar
            chmod +rwx ~/cxflow.jar

      - run:
          name: Execute CxSAST Scan using CxFlow
          command: |
            #~/cxcli/runCxConsole.sh Scan \
            #  -CxServer $CX_SERVER \
            #  -CxUser $CX_USER \
            #  -CxPassword $CX_PASSWORD \
            #  -ProjectName $CX_TEAM\/$CX_PROJECT \
            #  -LocationType folder \
            #  -LocationPath ~/project \
            #  -ReportXML ~//cxcli//$CX_PROJECT//$CX_PROJECT-results.xml \
            #  -ReportPDF ~//cxcli//$CX_PROJECT//$CX_PROJECT-results.pdf \
            #  -Comment "git $CIRCLE_BRANCH@$CIRCLE_SHA1" \
            #  -verbose
            java -jar ~/cxflow.jar --spring.config.location=~/project/application.yml --scan --cx-team="Cx NA Team\CxPhil" --cx-project="checkmarxSE" --app=10137 --bug-tracker="WAIT"

            #java -jar /app/cx-flow.jar --spring.config.location=./application.yml \
            #  --scan \
            #  --cx-team="$CX_TEAM" \
            #  --base-url="$CX_SERVER" \
            #  --cx-project="$CX_PROJECT-$CIRCLE_BRANCH" \
            #  --cxflow.bugTracker="none" \
            #  --f=.


      #- run:
      #    name: Moving Artifacts
      #    command: |
      #      mkdir ~/artifacts
      #      mv ~/cxcli/$CX_PROJECT/* ~/artifacts

      # Store the generated reports with the build logs in CircleCI
      #- store_artifacts:
      #    path: ~/artifacts
      #    destination: sast_results  
