version: 2
jobs:
  build:
    docker:
      - image: atlassian/default-image:2
    steps:
      - checkout
 
      - run:
          name: Install CxCLI Plugin
          command: |
            wget -O ~/cxcli.zip https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-2020.2.18.zip
            unzip ~/cxcli.zip -d ~/cxcli
            chmod +x ~/cxcli/runCxConsole.sh

      - run:
          name: Execute CxSAST Scan
          command: |
            ~/cxcli/runCxConsole.sh Scan \
              -CxServer $CX_SERVER \
              -CxUser $CX_USER \
              -CxPassword $CX_PASSWORD \
              -ProjectName "$CX_TEAM\\$CX_PROJECT" \
              -LocationType folder \
              -LocationPath ~/project \
              -Comment "git $CIRCLE_BRANCH@$CIRCLE_SHA1" \
              -verbose
